name: Weekly Sales Report Automation

on:
  schedule:
    - cron: '30 6 * * 1'  # Every Monday at 6:30 AM UTC (11:30 AM IST)
  workflow_dispatch:  # This allows manual triggering of the workflow from GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run weekly sales report script
        run: |
          python weekly_sales_report.py
