name: Weekly Sales Report Automation

on:
  schedule:
    - cron: '0 6 * * 1'  # This will run every Monday at 6:00 AM UTC (11:30 AM IST)
  workflow_dispatch:  # Allows manual triggering of the workflow if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

   - name: Install dependencies
  run: |
    pip install -r config/requirements.txt
    # Install dependencies from requirements.txt

    - name: Run weekly sales report script
      run: |
        python weekly_sales_report.py  # Your Python script to run the sales report automation

